### ISSUE TITLE
25 posts only

### ISSUE THREAD

**Issue by Darkpte** [ripmeapp2/ripme#11]
* Ripme version: 1.7.94
* Java version: 
* Operating system: Windows 10 version 20H2 (Os Build 19042.804)
* Exact URL you were trying to rip when the problem occurred: random xhamster photo album
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
download a full xhamster album 

## Actual Behavior

downloaded just the first 25 photos only and left the others undownloaded

**Comment by soloturn** [comment]
@Darkpte mind trying the newest build, it has an exact version number? download from https://github.com/ripmeapp2/ripme/actions.

**Comment by Darkpte** [comment]
it solved the problem but downloaded 48 pictures instead of 25, the rest is not downloaded

**Comment by soloturn** [comment]
@Darkpte which version does it display, just to be sure?

**Comment by Darkpte** [comment]
1.7.94 version

**Comment by soloturn** [comment]
this is not the newest @Darkpte, check on https://github.com/ripmeapp2/ripme/releases. it should not have an effect on this functionality though.

**Comment by Darkpte** [comment]
no good @soloturn, it seems someone having the same problem

**Comment by soloturn** [comment]
ok, let me close this one then, and leave #21 open as it mentiones the newest version and a url to test.
