### ISSUE TITLE
A JNI error occured

### ISSUE THREAD

**Issue by mimium** [ripmeapp2/ripme#110]
* Ripme version: ripme-2.1.2-3-ea90b172

* Java version:  
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

* Operating system:  Win 10 v 21H2 19044.2075

* Please include any additional information about how to reproduce the problem:

## Expected Behavior

ripme should run.

## Actual Behavior

ripme is not running, A JNI error occures instead.

![ripme_err01](https://user-images.githubusercontent.com/21373884/193052687-3026bb9a-2225-4743-a9d2-2de54c3359ed.PNG)

![ripme_err02](https://user-images.githubusercontent.com/21373884/193052764-9bc9c7c8-35c5-448d-8917-2bd6448c31e3.PNG)

**Comment by soloturn** [comment]
please use java-17.
