### ISSUE TITLE
create a release via github action, containing git hash in version

### ISSUE THREAD

**Issue by soloturn** [ripmeapp2/ripme#12]
currently the release process is very good, but slightly complex, and not automated. [ripme2app](https://github.com/ripmeapp2/ripme) contains a github workflow, which uploads a binary as artefact on every build. this has three drawbacks. first, the jar is within a zip, second, the zip is hidden within the github action menu, and third, the version number is fixed, so it is difficult to tell if it is newer or not.

to upload, a github workflow action could be implemented, like done[ here releasing paru](https://github.com/Morganamilo/paru/blob/master/.github/workflows/build.yml), which then [ends up in github releases].(https://github.com/Morganamilo/paru/releases)

a version number could be the last release tag, plus the count of commits since the last release, plus the git hash. the distance since the last release allows to determine what version is newer, e.g. 1.7.94.r13 is newer than 1.7.94.r11. it could be generated like this:
```
> git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
1.7.94.r11.g1742995e
```
another possibility would be to use some plugin which generates a build number, e.g.:
* [jgitver plugin, for maven or gradle](https://github.com/jgitver/jgitver-maven-plugin)
* [palantir plugin, for gradle](https://github.com/palantir/gradle-git-version)
* ...

**Comment by soloturn** [comment]
version calculation is done now with jgitver gradle plugin. does exist also for maven in case somebody wants to continue maintaining the mvn build.

**Comment by soloturn** [comment]
a development build is published, but there is no notion of "branch" yet. e.g. "latest-<branchname>", instead of "latest". or - produce it on branch "main" only.

**Comment by soloturn** [comment]
@saladzic should we try a real release?

**Comment by saladzic** [comment]
@soloturn I think it's time for a release ;)

**Comment by soloturn** [comment]
@saladzic i tried but for a reason unknown to me jgitver does not detect the release tag when building. what i also do not find ideal is that we produce too many interim versions which may confuse people which one to download now ... what is your thought about it?

**Comment by soloturn** [comment]
found how to throw these away, just delete the tags, e.g. with

```
git push origin -d <tag>
```
