### ISSUE TITLE
RipMe "rip.properties" file does not change properties of RipMe

### ISSUE THREAD

**Issue by Zh1nu** [ripmeapp2/ripme#122]
* Ripme version: ripme-2.1.3-7-3545cfbd.jar (tried earlier also)
* Java version: java version "19.0.1" 2022-10-18
* Operating system: Microsoft Windows [Version 10.0.19044.2130]
* Exact URL you were trying to rip when the problem occurred: none
* Please include any additional information about how to reproduce the problem:
Either edit rip.properties before you compile file, or open .jar and edit the rip.properties file in there.

## Expected Behavior

"rip.properties" would change Twitter API key and other settings in RipMe

## Actual Behavior

File is ignored, RipMe starts up with default settings. API key is not changed. 

Note: Is there a way to change the API keys using the GUI?

**Comment by soloturn** [comment]
could you please look if there is a properties file in another location?
