### ISSUE TITLE
.jar file not available to download when going to latest release

### ISSUE THREAD

**Issue by Cookielover118** [ripmeapp2/ripme#125]
* Ripme version: current
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred: https://github.com/ripmeapp2/ripme/blob/main/releases
* Please include any additional information about how to reproduce the problem:  go to https://github.com/ripmeapp2/ripme/blob/main/releases

## Expected Behavior

Expect to be able to download the .jar file when going to the latest releases on github
## Actual Behavior

404 page not found error

**Comment by soloturn** [comment]
the latest is on:
https://github.com/ripmeapp2/ripme/releases/download/latest-main/ripme-2.1.3-7-3545cfbd.jar

you have an example where such a link you post works?  please reopen in case.

**Comment by Cookielover118** [comment]
Thank you for the link.  I am excited to try the software.  Is there a way to update the main page (https://github.com/ripmeapp2/ripme)  so that the latest version link works.  If not 
Right now  following the link on the project page generates this error:

The 'ripmeapp2/ripme' repository doesn't contain the 'releases' path in 'main'.  

Thank you again.
