### ISSUE TITLE
Baraag "No images found"

### ISSUE THREAD

**Issue by blue-popsicle** [ripmeapp2/ripme#126]
* Ripme version: v2.1.2-23-e5438e85
* Java version: "18.0.1" 2022-04-19
* Operating system: Windows 10 Version 21H2 (OS Build 19044.2486)
* Exact URL you were trying to rip when the problem occurred: https://baraag.net/@Necrosmos/media (NSFW)

## Expected Behavior
Paste link to baraag gallery
Press the "Rip" button
RipMe downloads all images from the baraag album

## Actual Behavior
Paste link to baraag gallery
RipMe states, in green text, "baraag album detected"
Press the "Rip" button
RipMe claims that it starts downloading and that it completes the rip
RipMe states: "No images found at https://baraag.net/@Necrosmos/media"
No images have been downloaded

**Comment by soloturn** [comment]
closing, nobody sent a patch.
