### ISSUE TITLE
Imagefap Gallery Issue

### ISSUE THREAD

**Issue by Solumgam** [ripmeapp2/ripme#127]
* Ripme version: 2.12-23-e5438e85
* Java version: "18.0.1"
* Operating system: Windows 10 Version 21H2 (OS Build 19044.2486)
* Exact URL you were trying to rip when the problem occurred: https://www.imagefap.com/gallery/11018095 (NSFW)

## Expected Behavior

Paste link to gallery
Press the "Rip" button
RipMe downloads all images from the album

## Actual Behavior
Paste link to gallery
Ripme only downloads the first page of the gallery

**Comment by Muther11-cyber** [comment]
Ripme version: 2.12-23-e5438e85
Java version: "18.0.1"
Operating system: Windows 10 Version 21H2 (OS Build 19044.2486)
Exact URL you were trying to rip when the problem occurred: https://www.imagefap.com/pictures/11031749/Azshara (NSFW)
Expected Behavior
Paste link to gallery
Press the "Rip" button
RipMe downloads all images from the album

Actual Behavior
Paste link to gallery
Ripme only downloads the first page  (24 pics) of the gallery

**Comment by brantspar** [comment]
I am able to reproduce and fix the issue (simple renaming of URLs imagefap side)

I am working on fixing also the `timeout as a throttle` issue and will open a PR for both.

Stay tuned

**Comment by soloturn** [comment]
cool @brantspar

**Comment by brantspar** [comment]
If you just want to use the updated JAR while the PR is reviewed I have uploaded it here
https://ufile.io/lw02929d

**Comment by Muther11-cyber** [comment]
> If you just want to use the updated JAR while the PR is reviewed I have uploaded it here https://ufile.io/lw02929d

I just an error saying it can't install... then file disappears...

**Comment by brantspar** [comment]
You need to download and run `java -jar ripme-2.1.3-10-c9c46d6a-fix_imagefap_single_page_issue.jar`

No double clicking on a jar :)

**Comment by kegg76** [comment]
is there somewhere where we can download this file for free ?
that website asks to purchase a monthly plan to download :-(

also, if you have the time and appetite to help, is there somewhere a Java 11 runtime ? because i can only find Java 8 in that form :-(

thanks !!!

**Comment by kegg76** [comment]
does anyone see this thread anymore ??  :-(
