### ISSUE TITLE
Motherless Gallery Issue

### ISSUE THREAD

**Issue by Muther11-cyber** [ripmeapp2/ripme#129]
Ripme version: 2.12-23-e5438e85
Java version: "18.0.1"
Operating system: Windows 10 Version 21H2 (OS Build 19044.2486)
Exact URL you were trying to rip when the problem occurred: https://motherless.com/GI962BB6E

Expected Behavior

Paste link to gallery
Press the "Rip" button
 RipMe downloads all images/video from the album

Actual Behavior
Paste link to gallery
Ripme only will not download any pics/video's

**Comment by medledan** [comment]
I think the devs abandoned this version too. This has been like the 2nd or 3rd time this app has been branches, fixed, and abandoned.

**Comment by soloturn** [comment]
@medledan feel free to submit a pull request.

**Comment by madrasminar** [comment]
The

> I think the devs abandoned this version too. This has been like the 2nd or 3rd time this app has been branches, fixed, and abandoned.

The last update was 3 weeks ago to 2.1.5 I am hoping they have not abandoned.

The error for me is none of the files from motherless are downloading.

**Comment by brantspar** [comment]
Please see this -> https://github.com/ripmeapp2/ripme/pull/194

The ripper was definitely broken as the rip operation would be marked as completed before all images/files were downloaded.
