### ISSUE TITLE
Please provde arm64 build

### ISSUE THREAD

**Issue by XargonWan** [ripmeapp2/ripme#130]
* Operating system: Raspberry Pie 4, Debian, arm64
* Please include any additional information about how to reproduce the problem: Please provide an arm64 build of ripme.

## Expected Behavior

ripme starting to rip

## Actual Behavior

Error: Invalid or corrupt jarfile ripme.jar

**Comment by soloturn** [comment]
how did you get the jar file onto the system? google says that sometimes java-17 might be missing, but an older java should throw a different error. for sure you have seen links like: https://linuxhint.com/install-java-17-raspberry-pi/.
