### ISSUE TITLE
How to download lastest build question

### ISSUE THREAD

**Issue by Cookielover118** [ripmeapp2/ripme#132]
This question is about how to download the latest build from the project page.

How do you download this fork?
The link on the project page leads to a 404 error.
https://github.com/ripmeapp2/ripme/blob/main/releases

Is there a better link to check?  My apologies if this is a silly question.

**Comment by wvdberg** [comment]
https://github.com/ripmeapp2/ripme/releases/download/2.1.3/ripme-2.1.2-23-e5438e85.jar

**Comment by soloturn** [comment]
fixed download link
