### ISSUE TITLE
On Imagefap Galleries only first page is downloaded

### ISSUE THREAD

**Issue by kegg76** [ripmeapp2/ripme#135]
* Ripme version:2.0.4

On imagefap only the first page is downloaded.
Can someone be kind enough to fix this for 2.0.4 for all of us that don't have the latest Java installed ?

Thank you very much !!!!

**Comment by soloturn** [comment]
please install latest java, that is just a download.

**Comment by JuucJeck** [comment]
Now Imagefap galleries won't download at all.

**Comment by kegg76** [comment]
> Now Imagefap galleries won't download at all.

indeed, stopped working completely for imagefap  :-(

**Comment by brantspar** [comment]
See [this other issue](https://github.com/ripmeapp2/ripme/issues/138)
An alternative jar is provided
