### ISSUE TITLE
No Protocol Error

### ISSUE THREAD

**Issue by Solumgam** [ripmeapp2/ripme#137]
* Ripme version:  2.1.4
* Java version: 20.0.1
* Operating system: Windows 22H2 (19045.3086)
* Exact URL you were trying to rip when the problem occurred: https://www.imagefap.com/pictures/11417282/Whores%20pussies%20for%20your%20pleasure
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
Gets all images per page and saves them

## Actual Behavior
indicates that is reading the images but does not download/Save them. At the end it outputs "Rip Complete, saved to (Path)" Below in red is an error "no protocol"

**Comment by brantspar** [comment]
See [this other issue](https://github.com/ripmeapp2/ripme/issues/138)
Alternative jar provided
