### ISSUE TITLE
imagefap not working, gives message No Protocol:

### ISSUE THREAD

**Issue by kegg76** [ripmeapp2/ripme#138]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by brantspar** [comment]
I have fixed the issue in this PR -> https://github.com/ripmeapp2/ripme/pull/139

Updated and tested jar (while waiting for the PR to be accepted)
https://file.io/RtWpuLfl7yw2

**Comment by JuucJeck** [comment]
File deleted?

**Comment by brantspar** [comment]
https://uploadnow.io/f/dPhBG9F -> updated

**Comment by Solumgam** [comment]
Still no file?

**Comment by brantspar** [comment]
![image](https://github.com/ripmeapp2/ripme/assets/125783125/3ecfcd55-5dca-49d3-aefa-099a4e824a70)
File is there

**Comment by soloturn** [comment]
merged.

**Comment by soloturn** [comment]
if you could delete the not existing urls from the class would be cool. type https://www.imagefap.com/photo/... seems not to work.

**Comment by brantspar** [comment]
Not sure I follow. All URLs are valid - they now just reference a watermarked thumbnail.

**Comment by soloturn** [comment]
https://www.imagefap.com/photo/1474514869/?pgid=&gid=11365460&page=0 gives "no compatible ripper found".

**Comment by brantspar** [comment]
All the URL references at the top of the java class remain for compatibility as old URLs may still follow that pattern? I couldn't find a definite answer on this

**Comment by brantspar** [comment]
> `https://www.imagefap.com/photo/1474514869/?pgid=&gid=11365460&page=0`
This URL references a single image, not a gallery. As such it cannot be ripped...
