### ISSUE TITLE
Gradle stack trace of failed test

### ISSUE THREAD

**Issue by saladzic** [ripmeapp2/ripme#14]
Can someone set the Gradle CI to upload or display the stack trace from the failed test like before with Maven?

`FAILURE: Build failed with an exception.`

 `What went wrong:`
`Execution failed for task ':test'.`
    `There were failing tests. See the report at: file:///Users/runner/work/ripme/ripme/build/reports/tests/test/index.html`

`Try:`
`Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

**Comment by soloturn** [comment]
better now, reopen in case somebody is interested to further improve.
