### ISSUE TITLE
Cant run version 2.1.4 with java 17

### ISSUE THREAD

**Issue by tanja84dk** [ripmeapp2/ripme#142]
* Ripme version: ripme-2.1.4-38-836a7494.jar
* Java version: java 17.0.8 2023-07-18 LTS
  Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
  Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)
* Operating system: Widows 10, Version 21H2
* Please include any additional information about how to reproduce the problem:
had prior Java 17.0.4 and thought it still would be fine since it said default to java 17, but it failed starting.
Then I chose to update to the newest Java 17 (17.0.8) from https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html but that fails still the same way

## Expected Behavior
The expected behavior was it to start the java application but it wont start ( ripme-2.1.3-7-3545cfbd.jar starts fine )

## Actual Behavior
It wont start since it says its compiled with a to recent version

```shell
C:\Portable\RipMe>java --version
java 17.0.8 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)

C:\Portable\RipMe>java -jar ripme-2.1.4-38-836a7494.jar
Error: LinkageError occurred while loading main class com.rarchives.ripme.App
        java.lang.UnsupportedClassVersionError: com/rarchives/ripme/App has been compiled by a more recent version of the Java Runtime (class file version 64.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by Demirath** [comment]
I'm having a similar issue, Java 17 but 2.1.4 won't start even though 2.1.3 does

**Comment by ipkpjersi** [comment]
I have the same issue. Java 17 is class file version 61, so this is using Java 21 instead I guess even though it says Java 17 in the changelog?

**Comment by tanja84dk** [comment]
> I have the same issue. Java 17 is class file version 61, so this is using Java 21 instead I guess even though it says Java 17 in the changelog?

What it looks like for me then it looks like its Java 20 at this point
https://javaalmanac.io/bytecode/versions/

But the worrying part there is that Java 20 is really soon EOL ( next month ) because its not a LTS as 17 is ( looks like java 17 isnt EOL before 2030 because of LTS )

So yeah looks like I guess its gonna be Java 21 ( which I cant use ) or stay on the old release ( since the java 20 is EOL next month )

**Comment by madrasminar** [comment]
The error i get is

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/rarchives/ripme/App has been compiled by a more recent version of the Java Runtime (class file version 64.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

I downloaded the latest version of java from java website.

**Comment by ipkpjersi** [comment]
> > I have the same issue. Java 17 is class file version 61, so this is using Java 21 instead I guess even though it says Java 17 in the changelog?
> 
> What it looks like for me then it looks like its Java 20 at this point https://javaalmanac.io/bytecode/versions/
> 
> But the worrying part there is that Java 20 is really soon EOL ( next month ) because its not a LTS as 17 is ( looks like java 17 isnt EOL before 2030 because of LTS )
> 
> So yeah looks like I guess its gonna be Java 21 ( which I cant use ) or stay on the old release ( since the java 20 is EOL next month )
> 
> EDIT: I found out that if I build it myself from https://github.com/ripmeapp2/ripme/tree/2.1.5 ( with the java 17.0.8 2023-07-18 LTS ) then it worked fine, so I guess its because the build system they use for some reason are running a newer version then they state

I tried building from that but I just get 
```
For more details see https://docs.gradle.org/8.2.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> error: release version 17 not supported

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 30s
2 actionable tasks: 2 executed
> Task :compileJava FAILED
```

Mind sharing a built 2.1.5 jar that works with Java 17?

**Comment by tanja84dk** [comment]
> I tried building from that but I just get
> 
> ```
> For more details see https://docs.gradle.org/8.2.1/release-notes.html
> 
> Starting a Gradle Daemon (subsequent builds will be faster)
> > Task :compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileJava'.
> > error: release version 17 not supported
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 30s
> 2 actionable tasks: 2 executed
> > Task :compileJava FAILED
> ```
> 
> Mind sharing a built 2.1.4 jar that works with Java 17?

I'm so sorry to hear that keep in mind I'm also only a user and not a developer also unfortunally I'm at work so have to check when I'm home later.

First what OS are you on also are you sure you have the java 17 sdk and not only the jre ( sdk is for compiling )

Would you mind check what java --version and also dit you download from https://github.com/ripmeapp2/ripme/tree/2.1.5 or https://github.com/ripmeapp2/ripme/releases/tag/2.1.5

About that it works with java 17 for 2.1.4 yeah I think there has been some package updates in their build chain there have made the issue, like when ever I develop/compile things myself ( for me its another language ) then tests and compiles are always done in containers there is done in containers there is installed and then thrown away after for it to be so clean as possible, and that is why I suspect its a package update in their system of building releases there has made the issue

**Comment by ipkpjersi** [comment]
Ah I see, I'm a Java developer so don't worry, I do have the JDK. I am on Ubuntu 22.04 Linux and have JDK 17, java and javac are both saying I am using Java 17. Both the tree and the release tag are the same commit so that shouldn't be the issue. I tried compiling with the build.sh and manually with ./gradlew clean build -x test as well.

It would be nice if @soloturn could chime in on this since it seems like multiple people here are having issues with not being able to use Java 17, and with me not even being able to compile it.

**Comment by tanja84dk** [comment]
> Ah I see, I'm a Java developer so don't worry, I do have the JDK. I am on Ubuntu 22.04 Linux and have JDK 17, java and javac are both saying I am using Java 17. Both the tree and the release tag are the same commit so that shouldn't be the issue. I tried compiling with the build.sh and manually with ./gradlew clean build -x test as well.

No worries at all btw just got home for me my main is cpp, and the only real play I have done with java except a little poking from time to time were several years ago with minecraft

I'm in the middle of creating a docker container to test both with open-jdk 17 and oracle sdk 17 for you.

**Comment by ipkpjersi** [comment]
I had my JAVA_HOME set to Java 11 not 17 so that'd do it lol

I was able to build it now with Java 17, however, it looks like it builds a ripme-0.0.0-NOT_A_GIT_REPOSITORY.jar which of course has a version number of 0.0.0, so I still get the update prompt every launch: 
![image](https://github.com/ripmeapp2/ripme/assets/33754783/7e77954e-50c1-44da-9745-3d9ff7a6193e)

**Comment by Demirath** [comment]
I finally was able to run it by just installing the Java SDK 21 now that it's out of Beta

**Comment by tanja84dk** [comment]
> I had my JAVA_HOME set to Java 11 not 17 so that'd do it lol
> 
> I was able to build it now with Java 17, however, it looks like it builds a ripme-0.0.0-NOT_A_GIT_REPOSITORY.jar which of course has a version number of 0.0.0, so I still get the update prompt every launch: ![image](https://user-images.githubusercontent.com/33754783/271019941-7e77954e-50c1-44da-9745-3d9ff7a6193e.png)

Yeah that help alot and no worries at all.
I'm gonna try looking into how they set the version number this weekend to see if there is a way around that since I totally forgot that ( I'm normally using it cli based )



> I finally was able to run it by just installing the Java SDK 21 now that it's out of Beta

True that is also a possibility but unfortunately that aren't  a prober fix in a way.
Like for me I have several programs there rely on Java 17 which it says are supported and if I install lets say 21 and that is set as java home then it's breaking the other programs

**Comment by soloturn** [comment]
the version number is set by a gradle plugin: https://github.com/jgitver/gradle-jgitver-plugin, and it takes the version out of the last tag in the git repository. if you clone the repo and build it should do the trick https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository

@tanja84dk 20 nowadays you should not set java home any more. you set the bin directory into the path maybe or you call java with its full path. on windows as well linux. when ou call java, it knows where it is installed.

**Comment by tanja84dk** [comment]
> nowadays you should not set java home any more. you set the bin directory into the path maybe or you call java with its full path. on windows as well linux. when ou call java, it knows where it is installed.

@soloturn Well that is not true and you really knows that since when a program calls jre then it just calls the jre without a path so when several versions are in the path then it just choses the first it finds and you knows that

Like alot of software is compiled executable's java programs there doesnt deliver anything then a executable ( elf file in linux and .exe in windows ) and then internal rely on multiple jar files ( like my RSS reader RSSOwlnix ), eclipse etc

And that is specially there with my rss reader I saw that as soon java 21 also were installed then it failed right away since its posible using environment path ( and I have seen it several times just the one I remember off top of my head ) and possible that is only looks at program name in path

And I would believe it's because something between the jre 17 and jre 21 is depricated and removed

And have also seen it in other languages also over the time when things are deprecated and removed

So that is why what you say mostly wont work in practice

**Comment by ipkpjersi** [comment]
I cloned the git repo, I was able to build it and it built out a jar with filename ripme-2.1.5-4-3410a517.jar so I can now run this app again since I use Java 17 as my default now.

**Comment by soloturn** [comment]
> And that is specially there with my rss reader I saw that as soon java 21 also were installed then it failed right away since its posible using environment path ( and I have seen it several times just the one I remember off top of my head ) and possible that is only looks at program name in path

i checked RSSOwlnix, and it does NOT need JAVA_HOME set to build and run, see here:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rssowlnix

this thing contains a bug though, as it does not set the path to java before running rssowl which makes it fail as you described. 
```
$ cat /usr/bin/RSSOwlnix 
#!/bin/bash
export RSSOWLNIX_HOME=/usr/lib/RSSOwlnix
exec $RSSOWLNIX_HOME/RSSOwlnix "$@"
```

add it, and it works. same is valid to start eclispe as well, create a shell or windows cmd file and set the path to java before:

```
$ cat /usr/bin/RSSOwlnix 
#!/bin/bash
export PATH=/usr/lib/jvm/java-11-openjdk/bin:$PATH
export RSSOWLNIX_HOME=/usr/lib/RSSOwlnix
exec $RSSOWLNIX_HOME/RSSOwlnix "$@"
```

**Comment by tanja84dk** [comment]
That is biggest lie as I EVER has heard from a wannabe scripts kiddie and not even a newbie programmer

If you just took a look at the GitHub project you would see it's 99% Java 

https://github.com/Xyrio/RSSOwlnix there is a fork of the original https://github.com/rssowl/RSSOwl


And then showing from some literally fake info to hide your lies

And then thinking that everyone using your system where good luck using bash on windows specially where it's a exe it's called

Also does not change anything that you broken release literally doesn't work as stated in the release notes and hides behind it for months in silence on purpose and purposely won't believe the facts

**Comment by tanja84dk** [comment]
And it's you solely personally there is the issue since you purposely state a minimum Java version and then knowing and on purposely compile with a higher version in releases to fuck up everyone as literally the scumbag you are @soloturn !!!

Guess you also is a trump lover

**Comment by soloturn** [comment]
hahahaha, that logical connection between trump and a java versions seem to be unfounded :)i corrected the bug that it tested with both java-17 and java-21, and uploaded java-21. now it uploads java-17.
see here: 
https://github.com/ripmeapp2/ripme/releases/tag/latest-main
