### ISSUE TITLE
Unable to update from version 2.0.3 - throws 404 error for new jar fle

### ISSUE THREAD

**Issue by madrasminar** [ripmeapp2/ripme#144]
* Ripme version: 2.0.5-29-8710220b
* java version "1.8.0_381"
* Operating system: Version 10.0.19045.3208

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

"Check for updates" should update the version I have

## Actual Behavior

I get 404 error from Ripme Updater
![image](https://github.com/ripmeapp2/ripme/assets/99502578/06d005a8-ee70-47ce-9ac5-2945a3e8dd63)

**Comment by madrasminar** [comment]
I noticed that the URL in the updater is releases/download/2.1.4/ but the file is actually in /releases/download/2.1.5

Not sure if it helps.

**Comment by soloturn** [comment]
updated the 2.1.4 tag to point to commit 836a7494, and used 2.1.3-15-1b83dc68 for the previous.
