### ISSUE TITLE
When building from archive, calculated version is wrong and useless for version checks

### ISSUE THREAD

**Issue by txtsd** [ripmeapp2/ripme#145]
When building from an archive like [this one](https://github.com/ripmeapp2/ripme/archive/refs/tags/2.1.5.tar.gz), the version string created is `0.0.0-NOT_A_GIT_REPOSITORY`

When building from a [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ripme) as an AUR package maintainer (for the package [ripme](https://aur.archlinux.org/packages/ripme)), since the source files from the archive don't contain git information, [`fr.brouillard.oss.gradle.jgitver`](https://github.com/jgitver/gradle-jgitver-plugin) ends up using the git info of the AUR package resulting in a version string like `0.0.0-10-a902e065`.

Both of these cases make the version string useless for version checks against the latest version.

## Expected Behavior

Version should be set and queried explicitly.

## Actual Behavior

When git information is not available **in the correct directory**, the fallback mechanism should not create an incorrect version. It should be able to build the correct version string from the source files, and not rely solely on git information.

**Comment by soloturn** [comment]
why do you prefer to build from an archive instead of partial checked out git, @txtsd ?

**Comment by txtsd** [comment]
So in the AUR, there are build-from-archive packages ($pkgname), binary packages ($pkgname-bin), and build-from-source packages ($pkgname-{git,hg}). The first kind build from an archived tarball of the source (without vcs information), the second kind just package an official binary, and the last kind pull the source repo and build it that way. Users can choose whichever fits their use case per their convenience.

**Comment by soloturn** [comment]
you r not allowed to use the tag in git for the same source? i tried to look for an alternativre to jgitver, or a parameter to it to give a more reasonable default version than 0.0.0 ... but no luck.

**Comment by txtsd** [comment]
> you r not allowed to use the tag in git for the same source?

No the archives don't contain git information, and those packages mustn't depend on vcs software like git to be built.

> i tried to look for an alternativre to jgitver, or a parameter to it to give a more reasonable default version than 0.0.0 ... but no luck.

Why not just a string in a file?

**Comment by txtsd** [comment]
Excellent! Thank you.
