### ISSUE TITLE
Add support to gfycat/redgif Links that redirect to gifdeliverynetwork.com

### ISSUE THREAD

**Issue by BestRestUp3300** [ripmeapp2/ripme#15]
This been broken for a year. Still hasn't been fixed by the main dev.

Problem is some old gfycar links redirect to gifdeliverynetwork now. But ripme finds them as broken, since it doesnt read the redirect. 

Redgifs has been fixed in ripme, But gifdeliverynetwork is still broken. Something that might help the issue is that "https://gfycat.com/XXX" redirects to "https://www.gifdeliverynetwork.com/XXX" and if it is replaced by "https://www.redgifs.com/watch/XXX" , the link/video will still work on the redgifs/gifdeliverynetwork domain.

Maybe something can be implemented of sorts of replacing "https://gfycat.com/" or ""https://www.gifdeliverynetwork.com/" with "https://www.redgifs.com/watch/" if link fails as a band aid fix ?

https://github.com/RipMeApp/ripme/pull/1695

**Comment by soloturn** [comment]
your comment in RipMeApp#1695 says @borderline232 fork works. maybe one of you creates a pull request here so its clear(er) what makes it work? as main produces only a binary if all tests pass, i'll set the others to flaky.

**Comment by revanwolf** [comment]
RedGif links don't work either.

[ripme.log](https://github.com/ripmeapp2/ripme/files/6412160/ripme.log)

**Comment by borderline232** [comment]
I believe redgifs used gifdeliverynetwork to migrate the nsfw gfycats to redgifs, and most of them seem to just straight redirect the gfycat to redgifs instead of going to gifdeliverynetwork from what I understand. If you have any examples, I can change the logic on my fork and add a PR here as well.

**Comment by revanwolf** [comment]
RedGifs also seem to only download mobile version (issue #[1875](https://github.com/RipMeApp/ripme/issues/1875) on the original repo or #40 here).

**Comment by borderline232** [comment]
Added the fix on my fork, there's a new a release there along with getting selftext posts on reddit users (currently no way of disabling this).

**Comment by soloturn** [comment]
merged here, in 2.0.2.
