### ISSUE TITLE
Will not run 

### ISSUE THREAD

**Issue by Snkea** [ripmeapp2/ripme#152]
* Ripme version:ripme-2.1.7-11-0c6f8d85.jar
* Java version: java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) Client VM (build 25.391-b13, mixed mode, sharing)
* Operating system: windows 11 22h2 OS build 22621.2506

when try to run the .java file, it will say that java exception has occured and the java virutal machine will not run

**Comment by phillipredshirt** [comment]
Same issue with Java 1.8.0_361 on Windows 10.

"A Java Exception has occurred."

**Comment by soloturn** [comment]
you need java-17 long term edition at least, not the old java.
