### ISSUE TITLE
A Java Exception Has Occurred Error

### ISSUE THREAD

**Issue by yohuan94** [ripmeapp2/ripme#168]
* Ripme version: 2.1.8
* Java version: 1.8/1.8.0_391
* Operating system: Windows 11

Getting "A Java Exception Has Occurred" when trying to open .jar file

**Comment by robert-clayton** [comment]
Download the latest sdk and update your env vars to point to the new binaries

**Comment by senryusama** [comment]
got the same issue;
since I'm a total noob, and I don't want to mess things up by downloading the wrong stuff, is this the sdk you're talking about?
https://www.oracle.com/java/technologies/sdk-downloads.html

**Comment by spankmonkey69** [comment]
im having this same error, is there a way to fix that doesnt need an oracle account? im also pretty avg with code, how do you even point the env vars to the new binaries?

**Comment by samt108** [comment]
This issue can be closed, but maybe put a PSA somewhere?

**Comment by senryusama** [comment]
> im having this same error, is there a way to fix that doesnt need an oracle account? im also pretty avg with code, how do you even point the env vars to the new binaries?
> 
> Edit: going to https://www.oracle.com/java/technologies/downloads/ Downloading the one for windows fixed it for me, i was able to fun via cmd

Ah, so it was JDK, not SDK;
downloaded the installer, and now ripme startup fine.
Thanks!

**Comment by Mirrorman95** [comment]
Is this error fixed by installing JDK 17 or JDK 21? 'Cause I already installed 21, and it gave me this error, so I installed 17, and I'm having trouble running it with that, too.

**Comment by senryusama** [comment]
> I had to uninstall JDK 21 and install JDK 17 to fix this error.

For me it works...but I can't update it...

**Comment by schitzelfrank** [comment]
Installing jdk-23_windows-x64_bin with the MSI installer got it working for me. Installing it with the EXE did not work. 

https://stackoverflow.com/a/78054838
