### ISSUE TITLE
latest release lerns to check github

### ISSUE THREAD

**Issue by soloturn** [ripmeapp2/ripme#17]
versions 1.7.95 and onwards should check github for new releases, see here for hints: 

- https://api.github.com/repos/ripmeapp2/ripme/releases
- https://docs.github.com/en/github/administering-a-repository/linking-to-releases

change [UdateUtils.java](../blob/main/src/main/java/com/rarchives/ripme/ui/UpdateUtils.java).

**Comment by stalwartmonkey** [comment]
agreed

**Comment by soloturn** [comment]
it checks now, still towards the ripme.json file. the download overwrites the old jar as before.
