### ISSUE TITLE
Bug: Some Imagefap galleries will only partially download

### ISSUE THREAD

**Issue by Demirath** [ripmeapp2/ripme#179]
* Ripme versions: ripme-2.1.7-29-b080faae, ripme-2.1.8
* Java version: "21.0.2" 2024-01-16 LTS
* Operating system: Microsoft Windows Version 22H2
* Exact URL you were trying to rip when the problem occurred: (NSFW) https://www.imagefap.com/gallery/11981423
* Please include any additional information about how to reproduce the problem: 
Config:
![image](https://github.com/ripmeapp2/ripme/assets/25912441/17778710-c951-4171-a592-e5008cf577f2)

## Expected Behavior
All 249 images in gallery are downloaded.

## Actual Behavior
First 96 images are downloaded, then partway into next page, download ends with "Unable to extract image URL from single image page! Unable to continue" message. Retrying on both versions produces same result. 
![image](https://github.com/ripmeapp2/ripme/assets/25912441/d9fbed62-add8-4f25-8014-a796c3f1c439)

Have seen this behavior on a few other Imagefap galleries as well, no obvious pattern for which galleries or how many pages along it fails.

**Comment by Demirath** [comment]
Another gallery which fails: (NSFW) https://www.imagefap.com/gallery/12027064

Fails after 24 images instead of 96.

**Comment by joroto** [comment]
Does it consistently fail with these 2 galleries on the same image?

**Comment by Demirath** [comment]
The first link failed consistently for several days in a row; the second one I only tried once. I just retried both of them and they both worked, so I'm not sure what's going on anymore.

**Comment by joroto** [comment]
I tried them and they work as expected. I can implement a retry so if an image fails to be downloaded it won't stop the download but try again 2-3 times (waiting in between tries). Does this approach seem reasonable @soloturn ?
