### ISSUE TITLE
switch from log4j to log4j2

### ISSUE THREAD

**Issue by soloturn** [ripmeapp2/ripme#18]
log4j gives a potential security alert in [dependency alerts](/security/dependabot). while this is nothing security critical, best to upgrade to some recent log framework, like log4j2. switching over to different log location when debugging should not be done any more, as we have no sign anybody uses this feature. what you think @saladzic @PaaaulZ  ?

**Comment by saladzic** [comment]
I see it exactly the same. Unfortunately, I don't have enough experience to be more specific since I'm just a student xd
