### ISSUE TITLE
imagebam support

### ISSUE THREAD

**Issue by KTriebler** [ripmeapp2/ripme#185]
Hi, do you guys plan to incorporate imagebam.com album download support to the program? 

Thanks for the great app!

Cheers
KT

**Comment by joroto** [comment]
Imagebam is already supported and works correctly, I just checked.
What version of ripme are you using and what URLs are you trying to rip?

**Comment by KTriebler** [comment]
Hi Joroto,

 

Thanks for your reply.

 

I just tried it again with this gallery (caution: NSFW):

https://www.imagebam.com/gallery/bd563dcf1693a534313e4dcee513924d

 

The log says:

 

Downloading https://www.imagebam.com/gallery/bd563dcf1693a534313e4dcee513924d
Downloading next page
Rip complete, saved to C:\Users\[myusername]\Desktop\rips\imagebam_gallery Untitled Gallery

 

Or this gallery:

https://www.imagebam.com/gallery/7a7893ac6fd711b512a7a97b023e9e2c

 

Again, log says:

 

Downloading https://www.imagebam.com/gallery/7a7893ac6fd711b512a7a97b023e9e2c
Downloading next page
Rip complete, saved to C:\Users\[myusername]\Desktop\rips\imagebam_gallery Untitled Gallery

 

But in both cases there are no downloaded files, and no folder was created (neither in the rips folder nor anywhere else, I checked with the program Everything).

 

Program works very well with reddit downloads (subreddits or user pages), folders are created (same rip location as above) and files being downloaded, not so with imagebam however.

 

The version I'm using is v2.1.9-7-22e915df


 

Thanks and have nice weekend,

KT

 

Gesendet: Sonntag, 12. Mai 2024 um 00:39 Uhr
Von: "joroto" ***@***.***>
An: "ripmeapp2/ripme" ***@***.***>
Cc: "KTriebler" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [ripmeapp2/ripme] imagebam support (Issue #185)


 

Imagebam is already supported and works correctly, I just checked.
What version of ripme are you using and what URLs are you trying to rip?

**Comment by KTriebler** [comment]
Hi,

 

Did you have the time to look into this yet? Thanks for your efforts :)

 

Cheers

KT

 

Gesendet: Samstag, 18. Mai 2024 um 11:49 Uhr
Von: "Karsten Triebler" ***@***.***>
***@***.***
Betreff: Aw: Re: [ripmeapp2/ripme] imagebam support (Issue #185)



Hi Joroto,

 

Thanks for your reply.

 

I just tried it again with this gallery (caution: NSFW):

https://www.imagebam.com/gallery/bd563dcf1693a534313e4dcee513924d

 

The log says:

 

Downloading https://www.imagebam.com/gallery/bd563dcf1693a534313e4dcee513924d
Downloading next page
Rip complete, saved to C:\Users\[myusername]\Desktop\rips\imagebam_gallery Untitled Gallery

 

Or this gallery:

https://www.imagebam.com/gallery/7a7893ac6fd711b512a7a97b023e9e2c

 

Again, log says:

 

Downloading https://www.imagebam.com/gallery/7a7893ac6fd711b512a7a97b023e9e2c
Downloading next page
Rip complete, saved to C:\Users\[myusername]\Desktop\rips\imagebam_gallery Untitled Gallery

 

But in both cases there are no downloaded files, and no folder was created (neither in the rips folder nor anywhere else, I checked with the program Everything).

 

Program works very well with reddit downloads (subreddits or user pages), folders are created (same rip location as above) and files being downloaded, not so with imagebam however.

 

The version I'm using is v2.1.9-7-22e915df


 

Thanks and have nice weekend,

KT

 

Gesendet: Sonntag, 12. Mai 2024 um 00:39 Uhr
Von: "joroto" ***@***.***>
An: "ripmeapp2/ripme" ***@***.***>
Cc: "KTriebler" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [ripmeapp2/ripme] imagebam support (Issue #185)


 

Imagebam is already supported and works correctly, I just checked.
What version of ripme are you using and what URLs are you trying to rip?

**Comment by KTriebler** [comment]
Thanks!
