### ISSUE TITLE
Error when ripping from Erome?

### ISSUE THREAD

**Issue by dinhgp2** [ripmeapp2/ripme#192]
* Ripme version: 1.7.95
* Java version:  version 8
* Operating system:  10

* Exact URL you were trying to rip when the problem occurred: https://www.erome.com/a/rhM5eQRp
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Want to rip all videos from page. 

## Actual Behavior

Error message, then re attempt leads to saying it's already downloaded. Nothing gets downloaded

![Screenshot 2024-06-22 094319](https://github.com/ripmeapp2/ripme/assets/165954805/431b79f7-7216-4e8e-883e-a1896e44f8dd)

**Comment by joroto** [comment]
You are using a very old version. Please try with the latest 2.1.9 version you can find at:
https://github.com/ripmeapp2/ripme/releases/tag/2.1.9
I was not able to reproduce your issue using the latest version.
