### ISSUE TITLE
RipMe not starting anymore since latest Java update

### ISSUE THREAD

**Issue by KTriebler** [ripmeapp2/ripme#200]
* Ripme version: ripme-2.1.9-7-22e915df.jar
* Java version: java version "22.0.1" 2024-04-16
    Java(TM) SE Runtime Environment (build 22.0.1+8-16)
    Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)
* Operating system: Windows 11 Prof: Microsoft Windows [Version 10.0.22631.4037]

* Exact URL you were trying to rip when the problem occurred: n/a
* Please include any additional information about how to reproduce the problem: n/a

## Expected Behavior

Starting RipMe

## Actual Behavior

Since the latest Java update RipMe won't start anymore, it gives the error:
Title: Java Virtual Machine Launcher
Error message: A Java Exception has occurred.

**Comment by bandito52** [comment]
Saw solution posted in original RipMe. Just want to share it here as well in case others are facing same problem.

Installing [Java SE Development Kit 17.0.11](https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html) seems to fix issue for now.

**Comment by KTriebler** [comment]
Hello,

 

Yes, thanks, works like a charm :)

 

Best

KT

 
 

Gesendet: Sonntag, 01. September 2024 um 23:06 Uhr
Von: "Eric" ***@***.***>
An: "ripmeapp2/ripme" ***@***.***>
Cc: "KTriebler" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [ripmeapp2/ripme] RipMe not starting anymore since latest Java update (Issue #200)


 

Saw solution posted in original RipMe. Just want to share it here as well in case others are facing same problem.

Installing Java SE Development Kit 17.0.11 seems to fix issue for now.

**Comment by soloturn** [comment]
for me starting with java-22 works. can you ping the exact error message please? where do you get your openjdk version from?

**Comment by fercordovam** [comment]
One Question: for the 2.1.10 version which java version is needed?. Because I cannot open it.

**Comment by MaestroDaVinci** [comment]
> One Question: for the 2.1.10 version; which java version is needed?. Because I cannot run it. I am using [Java SE Development Kit 17.0.11](https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html)

I just installed the following the app worked:
[JDK Development Kit 21.0.4 ](https://www.oracle.com/java/technologies/downloads/?er=221886#java21)
