### ISSUE TITLE
E-hentai ripper not working

### ISSUE THREAD

**Issue by Aster92** [ripmeapp2/ripme#206]
* Ripme version: 2.1.9 and 2.1.10-21-c94a9543
* Java version: java 22.0.2 2024-07-16 | Java(TM) SE Runtime Environment (build 22.0.2+9-70) | Java HotSpot(TM) 64-Bit Server VM (build 22.0.2+9-70, mixed mode, sharing)
* Operating system: Windows 11 24H2

Tried to download multiple galleries of e-hentai, in the end i used 

https://e-hentai.org/g/3108622/ca9cb8fd80/

to run tests from 3 differents PCs in 2 countries.

The problem presented itself in version 2.1.9, and trying to resolve it, i updated to 2.1.10-21-c94a9543, where the same problem was present.
Last time it worked was on the 27 or 28 October (using 2.1.9)

## Actual Behavior

![Screenshot 2024-11-01 181036](https://github.com/user-attachments/assets/054afe64-b622-4121-a8ae-ca32c926c54b)

the only output is:
"Downloading https://e-hentai.org/g/3108622/ca9cb8fd80/
Rip complete, saved to G:\rips\e-hentai_Pixiv Asteroid 2033916
No images found at https://e-hentai.org/g/3108622/ca9cb8fd80/"

with a "Error: No images found at https://e-hentai.org/g/3108622/ca9cb8fd80/" as a header.

No folder gets created.

Same behavior for every link i used

**Comment by AZ18X** [comment]
Yes, I have the same problem. Please check it if possible. I have noticed that with other applications or extensions the same thing happens, like it does not detect the images in the link.

**Comment by Aster92** [comment]
This reinforces my hypothesis that they have changed the internal structure of the site or the image hosting
