### ISSUE TITLE
[Xhamster] Ripme stops downloading after 48 pictures

### ISSUE THREAD

**Issue by AmoraMasFina** [ripmeapp2/ripme#21]
* Ripme version : ripme-1.7.94-19-c52c34ab
* Java version: Version 8, update 241, build 1.8.0_241-b07.
* Operating system : Win 10.0.18363 Build 18363
* Exact URL you were trying to rip when the problem occurred : https://fr.xhamster.com/photos/gallery/damn-horny-amateur-brunette-enjoys-fucking-15471148

## Expected Behavior

Ripme should download the 155 pictures of this album.

## Actual Behavior

Ripme stops downloading after 48 pictures, and states "Already downloaded". (Can't get past the 2nd page ?)

**Comment by soloturn** [comment]
@ehump12000, @mukulj77 any opinion about this?

**Comment by mukulj77** [comment]
Yeah, I'm not sure which build you are using but my patch is working fine for me. If you would like, you can use it temporarily. https://github.com/mukulj77/ripme/releases/tag/1.7.94-rc

@soloturn I'mnot sure if my code is released yet. I tried with the latest nov 1.94 release and it didn't work. Quite sure that was before my patch was merged. But it stops at 24 images, i.e. 1 page. I haven't seen which package @AmoraMasFina is referring to which stops after two pages.

Let me know if you have any questions.

**Comment by AmoraMasFina** [comment]
@mukulj77 thanks I'll try with the release you link.

The package I used was ripme-1.7.94-19-c52c34ab : https://github.com/ripmeapp2/ripme/releases/download/latest-main/ripme-1.7.94-19-c52c34ab.jar

**Comment by soloturn** [comment]
@AmoraMasFina can you try this one pls:
https://github.com/ripmeapp2/ripme/releases/tag/latest-feature-xhamster-paging

@mukulj77 since you did the fix the versions deviated so much, in case the linked version does not work, you mind extracting your fix and create a pull request here?

**Comment by mukulj77** [comment]
@soloturn Hi, sure, let me have a look actually.

**Comment by soloturn** [comment]
no feedback, closing at the moment.
