### ISSUE TITLE
Can't download instagram posts

### ISSUE THREAD

**Issue by CynicalPlatapus** [ripmeapp2/ripme#22]
* Ripme version: v1.7.94-19-c52c34ab
* Java version: Version 8 Update 281 (build 1.8.0_281-b09)
* Operating system: Windows 10 Version 20H2 (OS Build 19042.867)
* Exact URL you were trying to rip when the problem occurred:
https://www.instagram.com/yaslenxoxo/

## Expected Behavior

Should download photos and videos from instagram page

## Actual Behavior

After download starts, it immediately stops and either says "Error: null" or "No images found"

**Comment by soloturn** [comment]
@CynicalPlatapus, would you mind copying the error out ot the log.txt in the download directory? especially if it is "Error: null".

**Comment by CynicalPlatapus** [comment]
@soloturn for some reason it suddenly started working, i have absolutely no idea why

it's been doing this occasionally lately, like it'll refuse to download from a twitter until i close and reopen it

**Comment by CynicalPlatapus** [comment]
@soloturn for some reason it just started working again, but after 93 downloads it stopped and says "no images found"

it's been a little buggy lately, like it'll refuse to download twitter posts unless i close and re-open it

**Comment by CynicalPlatapus** [comment]
@soloturn not seeing a log txt file anywhere

**Comment by soloturn** [comment]
let me close it until we have something more concrete.
