### ISSUE TITLE
Can I have repo access please

### ISSUE THREAD

**Issue by warte00** [ripmeapp2/ripme#27]
Sorry for this, could not find a way to contact.

```
remote: Permission to ripmeapp2/ripme.git denied to warte00.
```
Possibly because I created a new github account for this, it's got no history.

**Comment by warte00** [comment]
@soloturn

**Comment by soloturn** [comment]
@warte00 this happens when you fork it or clone local?

**Comment by warte00** [comment]
@soloturn Cloning worked, this was on pushing my branch to origin, to PR

**Comment by warte00** [comment]
```
~/git/ripme2/ripme$ git push --set-upstream origin feature/imagefap_logging_and_ASAP_downloading
Username for 'https://github.com': warte00
Password for 'https://warte00@github.com': 
remote: Permission to ripmeapp2/ripme.git denied to warte00.
fatal: unable to access 'https://github.com/ripmeapp2/ripme/': The requested URL returned error: 403
```

**Comment by warte00** [comment]
I suspect it's permissions because I also can't edit any files or manipulate branches in the github UI

**Comment by soloturn** [comment]
on the right top you have a fork button which clones the repo into your account, then you can clone and push from there. 
https://docs.github.com/en/github/getting-started-with-github/fork-a-repo
