### ISSUE TITLE
8muses : Illegal escape. at 47 [character 48 line 1]

### ISSUE THREAD

**Issue by revanwolf** [ripmeapp2/ripme#28]
* Ripme version: 1.7.94
* Java version: 
* Operating system: Windows

* Exact URL you were trying to rip when the problem occurred: https://comics.8muses.com/comics/album/Various-Authors/Chessire88
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

albums should download

## Actual Behavior

Error "Illegal escape. at 47 [character 48 line 1]" when downloading 8muses albums

**Comment by soloturn** [comment]
can you pls try newest version from https://github.com/ripmeapp2/ripme/releases (main) ?

**Comment by revanwolf** [comment]
I used the latest compiled version from this fork and also the latest release here and same issues.

**Comment by soloturn** [comment]
closing, if no version is specified in the bug report, difficult to trace.

**Comment by revanwolf** [comment]
> closing, if no version is specified in the bug report, difficult to trace.

It's easy, it's the last version compiled with the code from this repositery.

Tried right now with "ripme-1.7.96-1-c7af5c50" (compiled myself)

And no error illegal.escape but no files downloaded.

Now i get " Non-retriable status code 400 while downloading"
