### ISSUE TITLE
8muses  " Non-retriable status code 400 while downloading"

### ISSUE THREAD

**Issue by revanwolf** [ripmeapp2/ripme#31]
* Ripme version: ripme-1.7.96-1-c7af5c50
* Java version: 1.8.0_281
* Operating system: Windows 7 & 10

* Exact URL you were trying to rip when the problem occurred: https://comics.8muses.com/comics/album/Various-Authors/Chessire88
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Download images from 8muses

## Actual Behavior

Folder are created but no files are downloaded with error  " Non-retriable status code 400 while downloading"

**Comment by revanwolf** [comment]
[ripme.log](https://github.com/ripmeapp2/ripme/files/6305424/ripme.log)

Including Log from ripme-1.7.96-3-431d382c compiled 13 April 2021 from this repository.

**Comment by soloturn** [comment]
if one does "view page source" and "inspect" in firefox, the page content differs. the image is inserted into the <a ><img src=..></a>

**Comment by soloturn** [comment]
lets close this, until somebody opens it for a current version or provides a pull request.
