### ISSUE TITLE
Instagram "Error:null" 

### ISSUE THREAD

**Issue by RockyBukake** [ripmeapp2/ripme#32]
* Ripme version: 1.7.94 and above
* Java version: 11.0.10
* Operating system: Linux (Pop_OS!  5.11.0-7612-generic 20.10~97a8d1a-Ubuntu)
* Exact URL you were trying to rip when the problem occurred:  Any instagram URL (i.e www.instagram.com/kimkardashian )
* Please include any additional information about how to reproduce the problem: Input instagram URL, press "Rip"

## Expected Behavior

It downloads Instagram posts

## Actual Behavior

Ripme displays : 
![Screenshot from 2021-04-15 20-12-43](https://user-images.githubusercontent.com/35773324/114925496-16e5bc80-9e27-11eb-88e1-90dbf780dbbb.png)
when ran from terminal the output for release 1.7.94 is : 
![Screenshot from 2021-04-15 20-01-42](https://user-images.githubusercontent.com/35773324/114925562-2b29b980-9e27-11eb-96ac-e48f93a9cfc9.png)
tested with multiple newer releases output is similar :
![Screenshot from 2021-04-15 20-04-10](https://user-images.githubusercontent.com/35773324/114925657-498fb500-9e27-11eb-9b85-e24b4297ef4d.png)

**Comment by RockyBukake** [comment]
Log file : [log.txt](https://github.com/ripmeapp2/ripme/files/6320616/log.txt)

**Comment by soloturn** [comment]
thank you! did not see the "getCallerClass is not supported" up to now as i had java8set. with java11 i got it as well, now fxed with #33. why for you it is "error null" i wonder as well. is it a language thing or pop linux java? i tried with
```
> locale
LANG=en_US.UTF-8
> java -jar build/libs/ripme-1.7.96-4-f587e175.jar 
07:03:46.490 [main] DEBUG com.rarchives.ripme.utils.Utils - Getting key select.save.dir in en_US value Select Save Directory
07:03:46.511 [main] DEBUG com.rarchives.ripme.utils.Utils - Getting key loading.history.from in en_US value Loading history from
...
07:04:15.221 [Thread-3] ERROR com.rarchives.ripme.ripper.AbstractRipper - Got exception while running ripper:
java.io.IOException: No images found at http://www.instagram.com/kimkardashian
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:81) ~[ripme-1.7.96-4-f587e175.jar:1.7.96-4-f587e175]
```
on the first try, with java8, your link worked. subsequent tries did not work. switching the java version did not help. deleting the "save" directory did not help. delete ~/cconfig/ripme directory did not help. i am wondering if i overlooked where ripme stores information - as it worked one time and other time not. or instagram behaves different if one gets content  again. did you see such behaviour?

**Comment by soloturn** [comment]
@iProdigy you fixed that once in https://github.com/RipMeApp/ripme/pull/1722 - you v got any ideas?

**Comment by RockyBukake** [comment]
> thank you! did not see the "getCallerClass is not supported" up to now as i had java8set. with java11 i got it as well, now fxed with #33. why for you it is "error null" i wonder as well. is it a language thing or pop linux java? i tried with
> 
> ```
> > locale
> LANG=en_US.UTF-8
> > java -jar build/libs/ripme-1.7.96-4-f587e175.jar 
> 07:03:46.490 [main] DEBUG com.rarchives.ripme.utils.Utils - Getting key select.save.dir in en_US value Select Save Directory
> 07:03:46.511 [main] DEBUG com.rarchives.ripme.utils.Utils - Getting key loading.history.from in en_US value Loading history from
> ...
> 07:04:15.221 [Thread-3] ERROR com.rarchives.ripme.ripper.AbstractRipper - Got exception while running ripper:
> java.io.IOException: No images found at http://www.instagram.com/kimkardashian
> 	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:81) ~[ripme-1.7.96-4-f587e175.jar:1.7.96-4-f587e175]
> ```
> 
> on the first try, with java8, your link worked. subsequent tries did not work. switching the java version did not help. deleting the "save" directory did not help. delete ~/cconfig/ripme directory did not help. i am wondering if i overlooked where ripme stores information - as it worked one time and other time not. or instagram behaves different if one gets content again. did you see such behaviour? in case you as well get a different error now, please change the title of the ticket.

Negative. I did not experience that behavior, tried it on my Arch machine and results were identical, could it be related with how Instagram behaves to different user-agents ? I noticed that with a user-agent switcher extension enabled to "Windows / Chrome 87" on my Firefox and Brave Browser, Instagram would redirect to instagram.com/accounts/login, after clearing cookies and disabling the extension, that no-longer happens and let's me see the page again.

**Comment by soloturn** [comment]
@RockyBukake i debugged it briefly and it went into json ripper where the images were there, but the parsing of it is broken. i am not sure when it goes one of the 2 code paths.

**Comment by professorkilo** [comment]
same error for me every time
"Rip complete, saved to blah"
null

RipMe v1.7.94 in Kali and in Win10 [Java 8.281]

**Comment by terminalwhoami** [comment]
Same issue, unless I use an instagram session ID.

I did get locked out of my instagram a few days ago, and I think it might be related.  May want to implement a rate limiter for instagram as well.

**Comment by geraldlemelleii** [comment]
This issue seems to be happening on DeviantArt as well. It did work on Furaffinity though. I'm wondering if there's some kind of firewall installed on these sites that make it harder to rip them?

**Comment by KaoNinjaratzu** [comment]
This issue seems to be happening on DeviantArt as well. It did work on Furaffinity though. I'm wondering if there's some kind of firewall installed on these sites that make it harder to rip them?

**Comment by soloturn** [comment]
@tush-r @cariah you have an opinion here?

**Comment by soloturn** [comment]
@terminalwhoami here they write that before 5000 / hr were accepted, and now 200 / hr:
https://experienceleague.adobe.com/docs/livefyre/using/streams/c-instagram-rate-limiting.html?lang=en#streams

**Comment by Tush-r** [comment]
> @terminalwhoami here they write that before 5000 / hr were accepted, and now 200 / hr:
> https://experienceleague.adobe.com/docs/livefyre/using/streams/c-instagram-rate-limiting.html?lang=en#streams

Are you still having issues with this?
I don't really use the app. I can get something out on the weekend( no promises though).

**Comment by terminalwhoami** [comment]
@Tush-r I haven't tried without a session ID lately, also don't rip instagram that much.  trying to be cautious so they don't ban my account.

**Comment by LP560** [comment]
> @terminalwhoami here they write that before 5000 / hr were accepted, and now 200 / hr:
> https://experienceleague.adobe.com/docs/livefyre/using/streams/c-instagram-rate-limiting.html?lang=en#streams

Even without hitting the rate limit i still get these errors

**Comment by robinhugy** [comment]
tried https://github.com/ripmeapp2/ripme/actions/runs/844309842
but no luck, same error

**Comment by SH4LT1S** [comment]
Anyone fixed it?

**Comment by user5532** [comment]
Using latest green build. Still getting null..

**Comment by CynicalPlatapus** [comment]
> Using latest green build. Still getting null..

same

**Comment by tonystark2225** [comment]
Any Solution?

**Comment by SH4LT1S** [comment]
> Any Solution?

you wish

**Comment by terminalwhoami** [comment]
> Any Solution?

have you tried with an instagram session ID?

**Comment by terminalwhoami** [comment]
@soloturn did you ever get around to finding a solution for this? i remember you saying you tried to track it down, but couldn't figure it out.  If i don't use a session ID, i get null.  if i use one, i can rip a post.  This is on windows.

**Comment by soloturn** [comment]
interesting, @terminalwhoami , you do it like so: https://github.com/RipMeApp/ripme/issues/1380 ?
lets close it then ...
