### ISSUE TITLE
instagram error no images found

### ISSUE THREAD

**Issue by Darkpte** [ripmeapp2/ripme#35]
* Ripme version:
* Java version: 
* Operating system: windows 10 version 20H2 (os Build 19042.928)
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/the.successpreneur/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Download all Photos and videos

## Actual Behavior

No images found at https://www.instagram.com/successaddictives/

**Comment by soloturn** [comment]
duplicate of #32
