### ISSUE TITLE
[reddit] Mod removed post leaves an empty folder on the hard drive.

### ISSUE THREAD

**Issue by madhatr** [ripmeapp2/ripme#36]
v1.7.96-6-425a444a
Win10 x64 home.

The reason it is a problem is that it may make a person think that the Ripme app has failed to download the content.

This user (NSFW)
https://www.reddit.com/user/Lilbekkah101/

Steps
- back up and erase url_history.log
- rip the above user.

Has many empty folders after ripping.   Currently I found one issue I am investigating if there is any actual content missed.  Will open a separate issue if I find such an incident.

**Comment by soloturn** [comment]
old version.
