### ISSUE TITLE
[imgur via reddit] None of the reddit users imgur albums seems to be downloading.

### ISSUE THREAD

**Issue by madhatr** [ripmeapp2/ripme#37]
v1.7.96-6-425a444a
Win10 x64 home.

It seems just empty folders are saved on the drive in anticipation of the downloads.  None of the folders contain the images.
The links in the users profile are all albums. At this time I am not aware if directly linked single Imgur images work.

This user (NSFW)
https://www.reddit.com/user/Lilbekkah101/

![imgur album](https://user-images.githubusercontent.com/14855242/116087712-835a8a00-a677-11eb-83bf-cd91f1dd4c85.JPG)
![toocutetocare](https://user-images.githubusercontent.com/14855242/116087763-92d9d300-a677-11eb-81ea-ea3757c14d15.JPG)

**Comment by soloturn** [comment]
you have a log file? on linux this seems to work.

**Comment by madhatr** [comment]
I'll grab a log file.

**Comment by soloturn** [comment]
just copy pasted your url.
