### ISSUE TITLE
Pornhub Album ripper returning "No Images Found" error

### ISSUE THREAD

**Issue by ghost** [ripmeapp2/ripme#38]
* Ripme version: ripme-1.7.96-15-3ba1350f
* Java version: build 1.8.0_291-b10
* Operating system: Windows 10 Home 
* Exact URL you were trying to rip when the problem occurred: https://www.pornhub.com/album/4771891

Expected Behavior:
Download Pornhub Album to folder named Pornhub_4771891

Actual Behavior:
Link is recognized as PH, download starts, folder is created, rip completes and returns an error message saying "No images found" 

Log screenshot:
![Untitled 2](https://user-images.githubusercontent.com/80496391/116888284-45221500-abf9-11eb-9f5e-715f24bf3d70.png)

**Comment by soloturn** [comment]
lets close this, until somebody opens it for a current version or provides a pull request.
