### ISSUE TITLE
Redgifs ripper defaulting to mobile versions.

### ISSUE THREAD

**Issue by superrob1500** [ripmeapp2/ripme#40]
* Ripme version: 1.7.95
* Java version:  1.8.0_281-b09 (windows), build 11.0.11+9-Ubuntu-0ubuntu2.18.04 (Ubuntu)
* Operating system:  Windows 10, Ubuntu 18.04

* Exact URL you were trying to rip when the problem occurred: https://www.redgifs.com/watch/imperturbablecloudybullmastiff
* Please include any additional information about how to reproduce the problem:  happens downloading any redgifs.com links
## Expected Behavior

Downloads the best high resolution version available for a given link. Filename should be *001_ImperturbableCloudyBullmastiff.mp4*

## Actual Behavior

As of the last day or two the redgifs ripper has been defaulting to the mobile (smaller, lower quality) versions of found links (when scraping subreddits). Filename comes out as *001_ImperturbableCloudyBullmastiff-mobile.mp4* . 

This is a copy from an [identical issue](https://github.com/RipMeApp/ripme/issues/1875) with the main ripme repo. Since this repo seems more active I'm posting here as well, Hopefully if a solution is found we can share it with the main repo.

**Comment by mykeehu** [comment]
Any news about the fix? :)

**Comment by myns23** [comment]
any update

**Comment by floopybird** [comment]
@borderline232 has linked to a fixed version on his fork over here. I haven't tested it yet, just passing along the link.

https://github.com/RipMeApp/ripme/issues/1866#issuecomment-845601507

 Perhaps it'll help guide a solution here.

**Comment by myns23** [comment]
any fix ?

**Comment by borderline232** [comment]
Got a fix on my fork here https://github.com/borderline232/ripme you can download in the releases section. Also added functionality to rip selftext posts on reddit (no way of disabling this atm)

**Comment by soloturn** [comment]
cherry picked here @borderline232 , should be in next release 2.0.2.
