### ISSUE TITLE
Twitter skips images if they are a reply to another tweet

### ISSUE THREAD

**Issue by Mojavve** [ripmeapp2/ripme#41]
* Ripme version: 1.7.95
* Java version: 1.8.0_191
* Operating system: Windows 10 20H2
* Exact URL you were trying to rip when the problem occurred: Any twitter profile where described behavior exists (For example, ripping https://twitter.com/JULIA_HOLTER/ will not rip https://twitter.com/JULIA_HOLTER/status/1370912304213073921 because its a reply in a thread however the image above it which starts the thread will be downloaded) .

* Please include any additional information about how to reproduce the problem: try to rip a twitter profile where an image is in a reply (not the beginning of a thread).  In tweets where it says "replying to @username" at the top, or tweets where it says "show this thread" and where it is not the start of the thread.  Attempting to rip /with_replies or /media does not change behavior.

## Expected Behavior

All images in profile download

## Actual Behavior

Images in reply chains are skipped over.

**Comment by D1g1K1d** [comment]
this can be corrected by locating the source file:
`src/main/java/com/rarchives/ripme/ripper/rippers/TwitterRipper.java`

and on line 124, changing:
`.append("&exclude_replies=true")`
to:
`.append("&exclude_replies=false")`

*make sure to leave the rest of the line's contents intact!*

then simply build a new .jar file to reflect this change. :D
