### ISSUE TITLE
RipMe will only download 120 images from XHamster galleries

### ISSUE THREAD

**Issue by Je-Te-Ma** [ripmeapp2/ripme#42]
* Ripme version: 1.7.95 and v2.0.0
* Java version:  "1.8.0_291"
* Operating system:  Microsoft Windows [Version 10.0.19042.1052]

* Exact URL you were trying to rip when the problem occurred: 
   https://xhamster.com/photos/gallery/bianca-kmiec-instagram-gallery-9297310 (gallery has 235 pics)
   https://xhamster.com/photos/gallery/eva-de-dominici-15238087 (gallery is only 129)

tried several others with same result
* Please include any additional information about how to reproduce the problem:
Went into the History tab and see that the # column never shows more than 120 for this site in particular so it seems it's an old problem just never noticed it, galleries from other sites like twitter show higher numbers than that
## Expected Behavior
Download all pictures from Xhamster galleries.
Detail the expected behavior here.

## Actual Behavior
Downloads only 120 pictures even if the number of actual pictures in gallery is higher than that.
Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by soloturn** [comment]
is this better?
https://github.com/ripmeapp2/ripme/releases/tag/latest-feature-xhamster-paging

**Comment by Je-Te-Ma** [comment]
> is this better?
> https://github.com/ripmeapp2/ripme/releases/tag/latest-feature-xhamster-paging

Yes, I have tested with 3 galleries over 120 pics and they all downloaded complete. ThanX and sorry for the late response

**Comment by soloturn** [comment]
merged
