### ISSUE TITLE
Instagram ripper only ripping first 15 images or so.

### ISSUE THREAD

**Issue by SquaredDog** [ripmeapp2/ripme#44]
* Ripme version: Latest
* Java version:  build Version 8 Update 291 1.8.0_291-b10
* Operating system:  Windows

* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/celinechenn_/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Downloading of all images

## Actual Behavior

Only downloading the first 15 images (1 or 2 pages)

**Comment by soloturn** [comment]
is this a duplicate of #32 ?

**Comment by terminalwhoami** [comment]
Looks like this issue still exists in the latest version of this fork, including when using a session id

**Comment by soloturn** [comment]
lets close this, until somebody opens it for a current version or provides a pull request.
