### ISSUE TITLE
How to Set up cookies to download from private list.

### ISSUE THREAD

**Issue by Darkpte** [ripmeapp2/ripme#46]
* Ripme version: 2.0.0
* Java version: Latest version
* Operating system: Windows 10
* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

I try to download upvoted links of my reddit account and it says 
(Status Code 403. You might be able to circumvent this error by setting cookies for this domain)
so how can I setup cookies for it

**Comment by soloturn** [comment]
you want to have a look at this commit, maybe it is similar for reddit?
https://github.com/ripmeapp2/ripme/commit/0aa8a257cc690da12a4458df6f1f3fe7fe721264

**Comment by soloturn** [comment]
no response ...
