### ISSUE TITLE
Erome rip error:  "Non-retriable status code 405 while downloading from..."

### ISSUE THREAD

**Issue by floopybird** [ripmeapp2/ripme#47]
* Ripme version:
ripme-2.0.1-12-30f4cf3a.jar

* Java version:

-> java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

* Operating system:

-> uname -a
Linux localhost.localdomain 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-> cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

* Exact URL you were trying to rip when the problem occurred:

*** WARNING: NSFW ***
https://www.erome.com/a/5Jey2zfK
*** WARNING: NSFW ***

## Expected Behavior

Download the erome album.

## Actual Behavior

14:37:20.796 [pool-2-thread-4] ERROR com.rarchives.ripme.ripper.DownloadFileThread - [!] Non-retriable status code 405 while downloading from https://s202.erome.com/183/5Jey2zfK/soQRyGDi.jpeg
14:37:20.816 [pool-2-thread-5] ERROR com.rarchives.ripme.ripper.DownloadFileThread - [!] Non-retriable status code 405 while downloading from https://s202.erome.com/183/5Jey2zfK/09RSDN6I.jpeg
...snip...more of the same error...snip...
downloading from https://s202.erome.com/183/5Jey2zfK/Ogtvl0Yl_720p.mp4
14:37:23.208 [pool-2-thread-3] ERROR com.rarchives.ripme.ripper.DownloadFileThread - [!] Non-retriable status code 405 while 

It's 405 errors all the way down. This just started happening recently.

It's the same error as reported over on the other ripme git repo:  https://github.com/RipMeApp/ripme/issues/1919

**Comment by floopybird** [comment]
The answer might be as simple as setting a referrer header. I was tinkering with wget and getting a similar error so I tried setting a referrer and it worked. Also tried user-agent first to make wget look more like a real  browser and that made no difference.

*** WARNING: NSFW test image used ***

-> wget https://s202.erome.com/183/5Jey2zfK/HaHYvNLg.jpeg
--2021-09-12 15:20:05--  https://s202.erome.com/183/5Jey2zfK/HaHYvNLg.jpeg
Resolving s202.erome.com (s202.erome.com)... 144.217.69.161
Connecting to s202.erome.com (s202.erome.com)|144.217.69.161|:443... connected.
HTTP request sent, awaiting response... 405 Not Allowed
2021-09-12 15:20:06 ERROR 405: Not Allowed.

-> wget --referer "erome.com" https://s202.erome.com/183/5Jey2zfK/HaHYvNLg.jpeg 
--2021-09-12 15:20:11--  https://s202.erome.com/183/5Jey2zfK/HaHYvNLg.jpeg
Resolving s202.erome.com (s202.erome.com)... 144.217.69.161
Connecting to s202.erome.com (s202.erome.com)|144.217.69.161|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 436323 (426K) [image/jpeg]
Saving to: ‘HaHYvNLg.jpeg

100%[================================================================================================================================================================>] 436,323     1.30MB/s   in 0.3s   

2021-09-12 15:20:12 (1.30 MB/s) - ‘HaHYvNLg.jpeg’ saved [436323/436323]

**Comment by bbbbrrrzzt** [comment]
Not sure if this is appropriate, but [gallery-dl](https://github.com/mikf/gallery-dl) has an option to print URLs of media to standard out. You can then use your `wget` setup to retrieve the media themselves.

An example using an intermediary file would be
```
gallery-dl -g https://www.erome.com/a/5Jey2zfK >> urls
wget --referer "erome.com" --input-file=urls
```

This doesn't use ripme, but hopefully this is nonetheless useful.
