### ISSUE TITLE
Xhamster ripper: no more than 60 galleries are put in queue

### ISSUE THREAD

**Issue by MarcoBorrini99** [ripmeapp2/ripme#50]
* Ripme version: 2.0.1
* Java version: openjdk version "1.8.0_292"
* Operating system: ArchLinux
* Exact URL you were trying to rip when the problem occurred: https://xhamster.com/users/gleanman/photos
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

In queue shoud be put abut 4.5k galleries

## Actual Behavior

In queue are put about 60 galleries thats' exactly the first page.

**Comment by saladzic** [comment]
I can't confirm that it's only ripping the first page. Are you sure that your IP address hasn't been flagged?

**Comment by MarcoBorrini99** [comment]
> I can't confirm that it's only ripping the first page. Are you sure that your IP address hasn't been flagged?

I wouldn't be able to manually browse the site...

**Comment by soloturn** [comment]
lets close this, until somebody opens it for a current version or provides a pull request.
