### ISSUE TITLE
ripme downloading the -mobile.mp4 from redgifs/gfycat

### ISSUE THREAD

**Issue by ANaPhOrAX** [ripmeapp2/ripme#53]
Is that intentional? If so; why? I want the proper quality mp4. 0 interest in the *-mobile.mp4

**Comment by soloturn** [comment]
@ANaPhOrAX no its not intentional, mind creating a pull request?

**Comment by ANaPhOrAX** [comment]
damn well tbh I've never done that before, I'm pretty nooby at github.. let me see if I can figure it out

**Comment by ANaPhOrAX** [comment]
okay well I did my best, hope I did a decent job https://github.com/RipMeApp/ripme/pull/1936

**Comment by soloturn** [comment]
oh, wow ... you targetted the original repo where i have no permission to merge. tried to get @borderline232 commits here with "git cherry-pick". pls try.

**Comment by ANaPhOrAX** [comment]
I know, but somehow when I clicked "create pull request" on this repo, it defaulted to that one (not even kidding), so I just thought it was intentional somehow
