### ISSUE TITLE
Vsco Ripper Broken

### ISSUE THREAD

**Issue by neurolancer** [ripmeapp2/ripme#58]
* Ripme version: 2.0.4-3-d1e1ff93
* Java version: 1.8.0_311
* Operating system: Microsoft Windows [Version 10.0.19044.1415]
* Exact URL you were trying to rip when the problem occurred: https://vsco.co/4evermoodz/gallery
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Vsco album should be downloaded.

## Actual Behavior

RipMe errors with "Error: null". This appears to be due to the request to /content/Static/userinfo returning a token value of "tkn":"000000000000000000000000000". This is rejected by the API as follows:

```
"description":"The provided token is no longer valid","errorType":"session_expired","httpStatusCode":401,"message":"The session has expired - Please sign in again"
```

Log snippet:

```
Trying to load cookies from config for vsco.co
Trying to load cookies from config for vsco.co
Could not get site id
Trying to load cookies from config for vsco.co
Could not profile images
Got exception while running ripper:
java.lang.NullPointerException: null
	at com.rarchives.ripme.ripper.rippers.VscoRipper.getURLsFromPage(VscoRipper.java:87) ~[ripme-2.0.4.jar:2.0.4-3-d1e1ff93]
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:122) ~[ripme-2.0.4.jar:2.0.4-3-d1e1ff93]
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:624) [ripme-2.0.4.jar:2.0.4-3-d1e1ff93]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Waiting for threads to finish
```

**Comment by neurolancer** [comment]
Update:

The getUserTkn function needs to be updated to use the value of the "vs" cookie set by the userinfoPage request rather than trying to get this value from the "tkn" json object. As a temporary fix, userTkn can be set manually to a "vs" cookie value on line 83 of VscoRipper.java.

**Comment by soloturn** [comment]
mind creating a pull request @neurolancer ?
