### ISSUE TITLE
JPEG on i.redgifs.com - JSONObject["video"] not found.

### ISSUE THREAD

**Issue by mykeehu** [ripmeapp2/ripme#60]
* Ripme version: 2.0.4-13-03e32cb7
* Java version: latest
* Operating system: Windows 10 latest

* Exact URL you were trying to rip when the problem occurred: I've got JSONObject["video"] not found. error on i.redgifs.com
* Please include any additional information about how to reproduce the problem:
* Check this (18+) link and stop on this link: https://i.redgifs.com/i/lumpybothaphid.jpg
* Grab link (18+) is here: https://www.reddit.com/user/PAL-Petite-Ass-Lover

**Comment by soloturn** [comment]
this does not work with older versions as well like 2.0.0, 2.0.1, 2.0.2?
https://github.com/ripmeapp2/ripme/releases

**Comment by mykeehu** [comment]
I tried it with version 2.0.1-14, the bug is there too

**Comment by mykeehu** [comment]
I have a new links for testing, 18+:
https://www.reddit.com/user/Regina_noir
and here is picture link:
https://redgifs.com/watch/lavendershadowyfeline
