### ISSUE TITLE
[Feature Request] Add a date field to download only pictures from the date specified

### ISSUE THREAD

**Issue by Lufou** [ripmeapp2/ripme#61]
It would be nice I think to add a field to specify a date or a timestamp from which the RipApp will download the content of the URL, for example for Twitter, download all images from an account after date X.

Of course by default the RipApp will still download all pictures but I think an optional field for a date to download only pictures from the date specified can be a cool add.

**Comment by soloturn** [comment]
cool idea, you d mind creating a pull request?
