### ISSUE TITLE
Failure to download Imgur content linked from a Reddit post: "[!] Failed to download for URL ..."

### ISSUE THREAD

**Issue by floopybird** [ripmeapp2/ripme#62]
* Ripme version:  latest release, ripme-2.0.4-13-03e32cb7.jar

Btw, I noticed today that the --version option doesn't spit out a version:

-> java -jar ripme-2.0.4-13-03e32cb7.jar --help
usage: java -jar ripme.jar [OPTIONS]
 -4,--skip404                  Don't retry after a 404 (not found) error
 -a,--append-to-folder <arg>   Append a string to the output folder name
 -d,--saveorder                Save the order of images in album
 -D,--nosaveorder              Don't save order of images
 -f,--urls-file <arg>          Rip URLs from a file.
 -h,--help                     Print the help
 -H,--history <arg>            Set history file location.
 -j,--update                   Update ripme
 -l,--ripsdirectory <arg>      Rips Directory (Default: ./rips)
 -n,--no-prop-file             Do not create properties file.
 -p,--proxy-server <arg>       Use HTTP Proxy server
                               ([user:password]@host[:port])
 -r,--rerip                    Re-rip all ripped albums
 -R,--rerip-selected           Re-rip all selected albums
 -s,--socks-server <arg>       Use socks server
                               ([user:password]@host[:port])
 -t,--threads <arg>            Number of download threads per rip
 -u,--url <arg>                URL of album to rip
 -v,--version                  Show current version
 -w,--overwrite                Overwrite existing files

-> java -jar ripme-2.0.4-13-03e32cb7.jar -v

-> java -jar ripme-2.0.4-13-03e32cb7.jar --version

...no output either way.

* Java version: 

-> java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

* Operating system: 

-> uname -a
Linux localhost.localdomain 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-> cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

* Exact URL you were trying to rip when the problem occurred:

:: (NSFW) Warning ::

Originally trying to rip a reddit user with the following URL and noticed the imgur error & missing file(s):
  https://reddit.com/user/HornyHamburger98

I then tested with a specific reddit post URL for that user and got the same error:
  https://www.reddit.com/r/gonewild/comments/rworh9/in_keeping_with_showing_you_how_wet_ive_been/

No error at all with the direct imgur URL but it's silently failing to d/l anything, there's just an empty directory left behind:

-> java -jar ripme-2.0.4-13-03e32cb7.jar -l ./rip -H /dev/null -4 -u "https://imgur.com/xL211zE"
-> ls -al rip/imgur_xL211zE/
total 0
drwxrwxrwx 1 nobody users 0 Jan  6 15:18 .
drwxrwxrwx 1 nobody users 0 Jan  6 15:19 ..

* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Rip the Reddit user, including their imgur hosted content.  :)

## Actual Behavior

Throws error, doesn't download the imgur file(s).

-> java -jar ripme-2.0.4-13-03e32cb7.jar -l ./rip -H /dev/null -4 -u "https://www.reddit.com/r/gonewild/comments/rworh9/in_keeping_with_showing_you_how_wet_ive_been/"                  
15:06:55.543 [pool-2-thread-1] ERROR com.rarchives.ripme.ripper.DownloadFileThread - [!] Failed to download for URL https://i.imgur.com/xL211zE.mp4

That file can be retrieved with wget...

-> wget https://i.imgur.com/xL211zE.mp4
--2022-01-06 15:07:06--  https://i.imgur.com/xL211zE.mp4
Resolving i.imgur.com (i.imgur.com)... 151.101.48.193
Connecting to i.imgur.com (i.imgur.com)|151.101.48.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4732727 (4.5M) [video/mp4]
Saving to: ‘xL211zE.mp4’
100%[===============================================================================================================================================================================================>] 4,732,727   16.8MB/s   in 0.3s   
2022-01-06 15:07:07 (16.8 MB/s) - ‘xL211zE.mp4’ saved [4732727/4732727]

**Comment by soloturn** [comment]
please try again with a new version, which catches exceptions and prints them into the log during loops.
