### ISSUE TITLE
Redgifs Broken

### ISSUE THREAD

**Issue by BestRestUp3300** [ripmeapp2/ripme#64]
* Ripme version: ripme-2.0.5-4-04508452
* Java version: Latest Java
* Operating system: Windows 11
* Exact URL you were trying to rip when the problem occurred: Andy Redgifs Profile
* Please include any additional information about how to reproduce the problem: Put a redgifs proflie

## Expected Behavior

To download the proflie vids

## Actual Behavior

Failed to load https://api.redgifs.com/v1/users/XXXX/gfycats?count=100 after 2 attempts

**Comment by soloturn** [comment]
i clicked the url and it gives "route not found" ?

**Comment by kgnfth** [comment]
> i clicked the url and it gives "route not found" ?

Because XXXX means REDACTED, is it really that difficult to understand
