### ISSUE TITLE
ImageFap terribly slow.

### ISSUE THREAD

**Issue by masterofobzene** [ripmeapp2/ripme#68]
* Ripme version: v1.7.95
* Java version: 1.8.0_321
* Operating system:  Windows10
* Exact URL you were trying to rip when the problem occurred: RANDOM

It takes like 3 seconds per photo.

CMD launched and got the log in realtime; this shows all the time:
![imagen](https://user-images.githubusercontent.com/94469116/154819711-2863d797-4e1b-4209-b2ea-137ed6f88ae1.png)

**Comment by wvdberg** [comment]
Could that be the normal rate limiting for the site? sleeping 3.6 seconds is not outlandish, and could also be logged by multiple threads all logging to your cmd terminal.

**Comment by wvdberg** [comment]
Also upgrade your version

**Comment by soloturn** [comment]
close per @wvdberg
