### ISSUE TITLE
Erome download is not working

### ISSUE THREAD

**Issue by Rounlet** [ripmeapp2/ripme#73]
* Ripme version: 2.1.0
* Java version: jre1.8.0_321, jdk 17.0.2
* Operating system: Windows11
* Exact URL you were trying to rip when the problem occurred:
   https://www.erome.com/a/NnZSTL2m **(warning, LBTG contents)**
* Please include any additional information about how to reproduce the problem:
 
I've been using rime without jdk, so I downloaded the latest jdk. 
After entering path into the system, it was finally possible to run the .jar file.

The problem was that the message "Other" has different root" came out, so I deleted the ripme folder in Local and tried again. 
As a result, the message no longer came out. 
However, I received a new message that the download failed. I will attach the log file. 
[ripme.log](https://github.com/ripmeapp2/ripme/files/8190927/ripme.log)

Thank you.

**Comment by elonnotmusk** [comment]
Same for me, did you find any solution? i think ripme have a download problem with MP4 files

**Comment by Rounlet** [comment]
> Same for me, did you find any solution? i think ripme have a download problem with MP4 files

Sadly, I haven't found it yet. I tried again with the new 2.1.1 version, but the problem still remains. 
Considering that the log record is the same as the 2.1.0 version, I think this problem has not been corrected yet.

**Comment by soloturn** [comment]
does it download no mp4, part of the mp4 or all mp4 before giving an error?
