### ISSUE TITLE
'other' has different root & other stuff

### ISSUE THREAD

**Issue by mokeWe** [ripmeapp2/ripme#74]
* Ripme version: 2.10
* Java version:  java 17 2021-09-14 LTS
* Operating system: Version 10.0.19043.1526
* Exact URL you were trying to rip when the problem occurred: https://reddit.com/r/pics
* Please include any additional information about how to reproduce the problem:
Not entirely sure how to reproduce the problem, as well as getting the 'other' has different root error I am also unable to select download directory and the URL list directory, when I click the buttons nothing happens. I think it is caused because it is trying to open a window with a directory that no longer exists (drive F:) however I cannot find where the directory is cached within the .jar.

## Expected Behavior

Able to open the download directory and URL list directory selector.

## Actual Behavior

Unable to do so, window does not appear when clicked and "'other' has different root" error when trying to download.

**Comment by soloturn** [comment]
thanks for reporting, setting to home directory if it does not exist any more.

**Comment by Luke-L** [comment]
im getting the same issue. tried java 18 and 17, same results....
