### ISSUE TITLE
[Feature request] Block URL

### ISSUE THREAD

**Issue by madhatr** [ripmeapp2/ripme#76]
Block certain URL.  Example, onlyfans.  Seen the program trying to endlessly follow onlyfans from reddit.

**Comment by soloturn** [comment]
not able to understand this one.

**Comment by madhatr** [comment]
For example I am ripping a reddit user and the posts sometimes contain links to onlyfans.  Instead of the ripper trying to rip I would like it to ignore onlyfans.
