### ISSUE TITLE
nhentai.net "Non-retriable status code 403 while downloading" error code on all new albums.

### ISSUE THREAD

**Issue by codeRetard** [ripmeapp2/ripme#77]
* Ripme version: v2.1.1-3-536339dd
* Java version: openjdk version "11.0.14" 2022-01-18 - OpenJDK Runtime Environment (build 11.0.14+9-suse-1.1-x8664) - OpenJDK 64-Bit Server VM (build 11.0.14+9-suse-1.1-x8664, mixed mode)
* Operating system: OpenSUSE Tumbleweed Version = 20220207

* Exact URL you were trying to rip when the problem occurred: https://nhentai.net/g/394674/ "(**NSFW**)"
* Please include any additional information about how to reproduce the problem: Entering the above link in the URL field of the RipMe GUI, and clicking on the Rip button.

## Expected Behavior

All the 26 pictures in the album to be downloaded

## Actual Behavior

Ripping the album will result in 100% error rate, and no pictures from the album are downloaded. The GUI throws the "_Non-retriable status code 403 while downloading_" error for each entry in the album. Interestingly this is only applicable to the recently added albums which are showcased under the New Uploads section of the front page of the website. Older albums such as https://nhentai.net/g/765/ "(**NSFW**)" still download fine with no issues what so ever.

**Comment by soloturn** [comment]
please try now, applied https://github.com/RipMeApp/ripme/pull/1978

**Comment by codeRetard** [comment]
> please try now, applied [RipMeApp#1978](https://github.com/RipMeApp/ripme/pull/1978)

Just checked, and the issue sadly still remains.
