### ISSUE TITLE
Recent JNI error

### ISSUE THREAD

**Issue by Runisco** [ripmeapp2/ripme#78]
* Ripme version: ripme-2.1.1-3-536339dd.jar
* Java version: "1.8.0_321"
* Operating system: Microsoft Windows [Version 10.0.19043.1586]

## Expected Behavior

The ripper should start up

## Actual Behavior

Error messages.
"Error:" A JNI error has occured, please check your installation and try again"
"A Java Exception has occurred"

ripme-2.0.5-29-8710220b.jar starts as expected
ripme-2.1.1-3-536339dd.jar throws the error

**Comment by soloturn** [comment]
version 2.1 is compiled for java-11 and up.
