### ISSUE TITLE
Not working with Java 1.8

### ISSUE THREAD

**Issue by thinkpad4** [ripmeapp2/ripme#79]
* Ripme version:2.1.1
* Java version: 1.8
* Operating system: Windows 7

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
To work
Detail the expected behavior here.

## Actual Behavior
Doesn't work
Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.
It's not working with Java 1.8 anymore.  Java 1.8 is still supported and will be supported forever says Oracle so please restore this working on Java 1.8

**Comment by soloturn** [comment]
here details what "oracle sustaining support" means, which one can buy from oracle:
https://www.oracle.com/us/support/library/lifetime-support-technology-069183.pdf

**Comment by soloturn** [comment]
version 2.0.x still works with java8. if you want you can help provide a version for it?

**Comment by thinkpad4** [comment]
@soloturn https://www.oracle.com/java/technologies/java-se-support-roadmap.html  Java 8 is a LTS.  The Extended Support uplift fee will be waived for the period March 2022 - December 2030 for Java SE 8.  So as you can see the support fee is waived.
