### ISSUE TITLE
Reddit problem

### ISSUE THREAD

**Issue by CashOver** [ripmeapp2/ripme#81]
* Ripme version:ripme-1.7.94-54-7c78f21c.jar
* Java version: 9
* Operating system: Windows 10
* Exact URL you were trying to rip when the problem occurred:
* https://www.reddit.com/user/Corivas/?sort=top&t=all
* Please include any additional information about how to reproduce the problem:
* I would like to let you know that you are having a problem with the download system, because every time you download large content, it stops all the time in the middle or even at the beginning of the download progress, I would like to know if you could fix this problem, stay giving error JSONObject["author"] not found and also not downloading all images from the page
*

**Comment by soloturn** [comment]
please try a more recent version.
