### ISSUE TITLE
RipMe cannot find author when username begins with a "_"

### ISSUE THREAD

**Issue by Klutronic** [ripmeapp2/ripme#83]
* Ripme version:
     > 2.1.1-17-b6ba9786
* Java version: 
     > java version "17.0.2" 2022-01-18 LTS
     > Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
     > Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
* Operating system: 
     > Windows 11 / 21H2 / 22000.613

* Exact URL you were trying to rip when the problem occurred:
     > https://www.reddit.com/user/_Maina_
* Please include any additional information about how to reproduce the problem:
     > Attempt to rip a user with an underscore as the first character of their username

## Expected Behavior
Detail the expected behavior here.

The user would rip properly

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

When a username starts with an underscore, RipMe cannot find the author.  
Exact error message: 

JSONObject["author"] not found.

Thanks

**Comment by madhatr** [comment]
I confirmed.  This is new, it used to work fine with usernames that began with _

**Comment by soloturn** [comment]
never tried this - there is a loop in the code which prints an exception now in debug mode instead of stopping.

**Comment by soloturn** [comment]
the unit test "testSelfPostRip" gets an error on windows, switched it off. you mind trying it ?

**Comment by madhatr** [comment]
Yes it is working in the newest build.
