### ISSUE TITLE
latest release auto downloaded

### ISSUE THREAD

**Issue by tokimcbongrip** [ripmeapp2/ripme#86]
latest release auto downloaded and ever since now the option to auto rip from clip board does not work anymore, before it updated i could right click urls or thumbnails and select copy link address and it would auto download and queue up more  to download. now i have to click the rip.me window paste the url in and click rip. really annoying after years of it just auto ripping from clipboard. i have un checked the auto rip from clipboard and rechecked it, still wont work...even tried shutting down and restarting my pc thinking maybe that was the issue but the problem is still there clearly a bug from the new version

**Comment by masterdjboner** [comment]
im having the same issue

**Comment by soloturn** [comment]
what is the last version working correctly?
