### ISSUE TITLE
Can't execute application with JRE 1.8

### ISSUE THREAD

**Issue by MeYHymN** [ripmeapp2/ripme#87]
* Ripme version: ripme-2.1.2-13-8b2304d4
* Java version:  SE Runtime Environment (build 1.8.0_331-b09)
* Operating system: Win7x64 Version  6.1 Build 7601 Serv Pack 1

* Exact URL you were trying to rip when the problem occurred:Any
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
Execute Program

Detail the expected behavior here.
Execute -> FAP -> Nap

## Actual Behavior
Banging head against desk trying to figure out how to install an alternative runtime environment.

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

Can't execute program only receive JNI errors. App has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
Seems there in no JRE past 1.8.

**Comment by soloturn** [comment]
maybe here:
https://stackoverflow.com/questions/70225754/java-11-jdk-for-windows-7-32-bit-system
