### ISSUE TITLE
reddit support help

### ISSUE THREAD

**Issue by CashOver** [ripmeapp2/ripme#92]
Ripme version: ripme-2.1.2-3-ea90b172.jar
Java version: 11
Operating system: Windows 10
Exact URL you were trying to rip when the problem occurred:
https://www.reddit.com/user/Corivas/?sort=top&t=all
Please include any additional information about how to reproduce the problem:
I would like to know if you could make a support, because the program only downloads half the amount
of images that you have on a page but you could update to download all images

**Comment by soloturn** [comment]
if you could debug it a little bit please? like described here e.g. ?
https://www.jetbrains.com/help/idea/debugging-your-first-java-application.html

**Comment by CashOver** [comment]
I'm sorry but I didn't understand

**Comment by soloturn** [comment]
would you mind helping to fix it?
