### ISSUE TITLE
Ripme crashing on startup

### ISSUE THREAD

**Issue by Scientist07** [ripmeapp2/ripme#93]
* Ripme version: 2.1.2-3
* Java version:  8 update 333
* Operating system:  Windows10 64bit

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

App opens normally.

## Actual Behavior
App does not open and instead displays:

- First window shows "Error A JNI error has occurred, please check your installation and try again." 

- Clicking ok then brings up a second window which shows "A Java exception has occurred."

I have uninstalled and reinstalled java but I'm getting the same errors.

**Comment by soloturn** [comment]
please use java11 or newer.
