### ISSUE TITLE
"Error: A JNI error has occurred, please check your installation and try again"

### ISSUE THREAD

**Issue by Scientist07** [ripmeapp2/ripme#96]
* Ripme version: 2.1.2.3
* Java version:  Version 8 Update 333
* Operating system:  Windows 10 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

App should open.

## Actual Behavior

Not opening. Error message: "A JNI error has occurred please check your installation and try again".
Clicking ok on that box shows: "A java exception has occurred".

**Comment by SevenInchAnaconda** [comment]
Had the same issue, you have to install Java SE 11+ to get it working.

**Comment by soloturn** [comment]
which link did you get this version from?

**Comment by soloturn** [comment]
needs java11

**Comment by Scientist07** [comment]
> Had the same issue, you have to install Java SE 11+ to get it working.

Thanks a lot man. My Java was telling me there were no updates. Got Java SE 18.0.1.1 and all's good now.
