### ISSUE TITLE
'other' has different root error?

### ISSUE THREAD

**Issue by SevenInchAnaconda** [ripmeapp2/ripme#97]
* Ripme version: 2.1.2
* Java version: 1.8.0
* Operating system: Win 10
* Exact URL you were trying to rip when the problem occurred: Every URL
* Please include any additional information about how to reproduce the problem: Just try and rip anything

## Expected Behavior

It should rip pages.

## Actual Behavior

Gives that error and doesn't rip anything.
![image_2022-06-29_004040095](https://user-images.githubusercontent.com/71599628/176304379-2ff6f2f0-3ff4-4a01-9d95-f87dfad44474.png)

**Comment by soloturn** [comment]
please use java11, not java8.

**Comment by SevenInchAnaconda** [comment]
> please use java11, not java8.

How do i switch from java8 to java11?
