### ISSUE TITLE
desuarchive.

### ISSUE THREAD

**Issue by Snkea** [ripmeapp2/ripme#99]
* Ripme version: ripme-2.1.2-14-827cc133
* Java version: version 8 Update 333 build 1.8.0-b02
* Operating system: Version 21h2 OS build 2200.795 Windows 11
[](https://desuarchive.org/tg/thread/85306506/#85306506)
* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
For the software to download the images from the board

Detail the expected behavior here.

## Actual Behavior
While it will download the images, it will also download copy of the same image but will add "s" at the end of the filesname, 
Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by soloturn** [comment]
you mind creating a pull request to fix it?
